import styles from '../../styles/Home.module.css';
import Head from 'next/head';
import Link from 'next/link';

export default function News() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Все новости</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <Link href={'/news/qu346'}>
            <a className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>
          </Link>
          <Link href={'/news/21653'}>
            <a className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
}
